site_name: Lazy Guide
site_description: JP Immersion Tool Lazy Guide
site_author: Xelieu
nav:
  - Home: 'lazy-guide/index.md'
  - Setup: 
    - Setup Anki: 'lazy-guide/setup.md'
    - Setup Yomichan: 'lazy-guide/setupAnki.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Xelieu
    - icon: fontawesome/brands/discord
      link: https://www.discordapp.com/users/719459399168426054
      name: xelieu
  analytics:
    provider: google
    property: G-GMJZ3SM36S
  generator: false
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang:
        - en
        - ja

copyright: |
  &copy; 2023 <a href="https://github.com/Xelieu"  target="_blank" rel="noopener">Xelieu</a>